[versions]
minecraft = "1.20"
yarn_mappings = "1.20+build.1"
fabric_loader = "0.14.22"
fabric_api = "0.83.0+1.20"
fabric_loom = "1.2.+"

lombok = "1.18.28"

toml4j = "0.7.2"

shadow = "8.1.+"
git = "3.0.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

toml4j = { module = "com.moandjiezana.toml:toml4j", version.ref = "toml4j" }

[plugins]
fabric_loom = { id = "fabric-loom", version.ref = "fabric_loom" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
git = { id = "com.palantir.git-version", version.ref = "git" }
